## 期约与异步函数

### 异步编程

异步行为是为了优化计算量而时间长的操作。只要不想为等待某个异步操作而阻塞线程执行，任何时刻都可以用。

#### 同步与异步

同步行为对应内存中的顺序执行的处理器指令。

异步行为类似于系统中断，即当前进程外部的实体可以触发代码执行。



早期的JS中，只支持定义回调函数来表明异步操作完成，串联多个异步操作会导致回调地狱。

```js
//异步返回值
//如果settimeout操作会返回一个有用的值。一个策略是给异步操作提供一个回调
function double(value,cb){
    setTimeout(()=>{cb(value*2)},1000)
}
double(3,(x)=>{console.log(x)});
//1秒后返回6
```

```js
//失败处理
//异步操作的失败处理也要考虑，所以出现了成功回调和失败回调。这种模式已经不可取了，因为必须在初始化异步操作时定义回调
function double(value,success,failure){
    setTimeout(()=>{
        try{
            if(typeof value !== 'number'){
                throw 'must a number'
            }
            success(value*2)
        }catch(e){
            //TODO handle the exception
            failure(e)
        }
    },1000)
}

const successCb = (x)=>{console.log('success'+x)}
const failureCb = (x)=>{console.log('failure'+x)}

double(3,successCb,failureCb);//success6
double('3',successCb,failureCb);//must a number
```

```js
//嵌套异步回调，显然随着代码越来越复杂，回调策略是不具备扩展性的
function double(value,success,failure){
    setTimeout(()=>{
        try{
            if(typeof value !== 'number'){
                throw 'must a number'
            }
            success(value*2)
        }catch(e){
            //TODO handle the exception
            failure(e)
        }
    },1000)
}

const successCb = (x)=>{
    double(x,(y)=>{console.log('success'+y)})
}
const failureCb = (x)=>{console.log('failure'+x)}

double(3,successCb,failureCb);//2s后输出
double('3',successCb,failureCb);//1s后输出
```

### 期约

状态值：待定（pending）、解决（resolved）、拒绝（rejected）

待定是期约的初始状态，在待定状态，期约可以落定为解决状态或者拒绝状态，且落定的状态是不可逆的。而且，不能保证期约必然会脱离待定状态。

期约的状态是私有的，所以只能在内部进行操作。内部操作在期约的执行器函数中完成。执行器有两个主要职责：初始化期约的异步行为和控制状态的最终转换。控制期约状态的转换是通过调用它的两个函数参数实现的。通常命名为resolve()和reject()。

```js
let p1 = new Promise((resolve,reject)=>{
    resolve()
})
let p2 = new Promise((resolve,reject)=>{
    reject()
})

setTimeout(console.log,0,p1);//Promise <resolved>
setTimeout(console.log,0,p2);//Uncaught (in promise)
```

```js
//状态不可撤销
let p = new Promise((resolve,reject)=>{
    resolve();
    reject();//无效
})
setTimeout(console.log,0,p);//Promise <resolved>
```

```js
//可设置定时退出的功能
let p = new Promise((resolve,reject)=>{
    setTimeout(reject,3000)
})
setTimeout(console.log,0,p);//Promise <pending>
setTimeout(console.log,4000,p);
//3s:Uncaught (in promise)
//4s:Promise <rejected>
```

```js
//Promise.resolve()静态方法，可以实例化一个解决的期约
//效果一样的
let p = new Promise((resolve,reject)=>resolve());
let p1 = Promise.resolve();
```

```js
//Promise.reject()静态方法，可以实例化一个拒绝的期约
//效果一样的
let p = new Promise((resolve,reject)=>reject());
let p1 = Promise.reject();
```

```js
//二元性
try{
    throw new Error('foo')
}catch(e){
    console.log(e)//Error: foo
}
//同步代码没有捕获期约抛出的错误，因为没有通过异步模式来捕获错误。
try{
    Promise.reject(new Error('bar'))//Uncaught (in promise) Error: bar
}catch(e){
    console.log(e)
}
```

#### 期约的实例方法

期约实例的方法是连接外部同步代码和内部异步代码之间的桥梁。这些方法可以访问异步操作返回的数据。

##### Thenable接口

```js
//在ES暴露的异步结构中，任何对象都有一个then()方法。
class MyThenable{
    then(){}
}
```

##### Promise.prototype.then()

```js
//为期约函数添加吹程序的主要方法，接收两个参数：onResolved处理程序和onReject处理程序。这两个参数都是可选的，如果提供的话，则会在期约分别进入解决和拒绝状态时执行

function onResolved(id){
    setTimeout(console.log,0,id,'resolved')
}
function onRejected(id){
    setTimeout(console.log,0,id,'rejected')
}

let p1 = new Promise((resolve,reject)=>{
    setTimeout(resolve,3000)
})
let p2 = new Promise((resolve,reject)=>{
    setTimeout(reject,3000)
})

p1.then(()=>onResolved('p1'),()=>onRejected('p1'));
p2.then(()=>onResolved('p2'),()=>onRejected('p2'));
//3s后
//p1 resolved
//p2 rejected

//传给then()的任何非函数类型的参数都会被静默忽略。如果只提供onReject参数，那就要咋onResolved参数位置上传入undefined。
function onResolved(id){
    setTimeout(console.log,0,id,'resolved')
}
function onRejected(id){
    setTimeout(console.log,0,id,'rejected')
}

let p1 = new Promise((resolve,reject)=>{
    setTimeout(resolve,3000)
})
let p2 = new Promise((resolve,reject)=>{
    setTimeout(reject,3000)
})

p1.then('1233');//非函数处理程序会被静默忽略
p2.then(null,()=>onRejected('p2'));//3s后  p2 rejected

//.then()返回一个新的期约实例
let p1 = new Promise(()=>{});
let p2 = p1.then();

setTimeout(console.log,0,p1)//Promise {<pending>}
setTimeout(console.log,0,p2)//Promise {<pending>}
setTimeout(console.log,0,p1===p2)//false

//这个新的实例基于onResolved处理程序的返回值构建。如果没有提供这个处理程序，则Promise.resolve()就会包装是哪个一个期约解决之后值。如果没有显示的返回语句，则Promise.resolve()会包装默认的返回值undefined
let p1 = Promise.resolve('foo')
let p2 = p1.then();
//调用then不传处理程序，则原样像后传
setTimeout(console.log,0,p2)
//这些都一样
let p3 = p1.then(()=>undefined)
let p4 = p1.then(()=>{})
let p5 = p1.then(()=>Promise.resolve())

setTimeout(console.log,0,p3)//Promise {<resolved>: undefined}
setTimeout(console.log,0,p4)//Promise {<resolved>: undefined}
setTimeout(console.log,0,p5)//Promise {<resolved>: undefined}

//如果有显示的返回值，则Promise.resolve()会包装这个值
let p6 = p1.then(()=>'bar')
let p7 = p1.then(()=>Promise.resolve('bar'))

setTimeout(console.log,0,p6)//Promise {<resolved>: "bar"}
setTimeout(console.log,0,p7)//Promise {<resolved>: "bar"}

//Promise.resolve()保留返回的期约
let p8 = p1.then(()=>new Promise(()=>{}));
let p9 = p1.then(()=>Promise.reject());

setTimeout(console.log,0,p8)//Promise {<pending>}
setTimeout(console.log,0,p9)//Promise {<rejected>: undefined}

//抛出异常会返回拒绝的期约
let p10 = p1.then(()=>{throw 'baz'});//Uncaught (in promise) baz
setTimeout(console.log,0,p10)//Promise {<rejected>: "baz"}

//返回错误值不会触发上面的拒绝行为，而会把错误对象包装在一个解决的期约中
let p11 = p1.then(()=>Error('qux'))
setTimeout(console.log,0,p11)//Promise {<resolved>: Error: qux


//onRejected处理程序类似
let p1 = Promise.reject('foo')
//调用then()时不传处理程序则原样向后传
let p2 = p1.then()//Uncaught (in promise) foo
setTimeout(console.log,0,p2)//Promise {<rejected>: "foo"}
		
//这些都一样
let p3 = p1.then(null,()=>undefined)
let p4 = p1.then(null,()=>{})
let p5 = p1.then(null,()=>Promise.resolve())

setTimeout(console.log,0,p3)//Promise {<resolved>: undefined}
setTimeout(console.log,0,p4)//Promise {<resolved>: undefined}
setTimeout(console.log,0,p5)//Promise {<resolved>: undefined}

//这些都一样
let p6 = p1.then(null,()=>'bar')
let p7 = p1.then(null,()=>Promise.resolve('bar'))

setTimeout(console.log,0,p6)//Promise {<resolved>: "bar"}
setTimeout(console.log,0,p7)//Promise {<resolved>: "bar"}

//Promise.resolve()保留返回的期约
let p8 = p1.then(null,()=>new Promise(()=>{}))
let p9 = p1.then(null,()=>Promise.reject())//Uncaught (in promise) undefined

setTimeout(console.log,0,p8)//Promise {<pending>}
setTimeout(console.log,0,p9)//Promise {<rejected>: undefined}

let p10 = p1.then(null,()=>{throw 'baz'})//Uncaught (in promise) baz
setTimeout(console.log,0,p10)//Promise {<rejected>: "baz"}

let p11 = p1.then(null,()=>{Error('qux')})
setTimeout(console.log,0,p11)//Promise {<resolved>: undefined}
```

##### Promise.prototype.catch()

```js
//用于给期约添加拒绝处理程序。这个方法只接收一个参数：onRejected处理程序。事实上这是一个语法糖，相当于调用Promise.prototype.then(null,onRejected)
let p = Promise.reject();
let onRejected = function(e){
    setTimeout(console.log,0,'reject');
};

p.then(null,onRejected);//reject
p.catch(onRejected);//reject

//Promise.prototype.catch()返回一个新的期约实例
let p1 = new Promise(()=>{});
let p2 = p1.catch();

setTimeout(console.log,0,p1)//Promise {<pending>}
setTimeout(console.log,0,p2)//Promise {<pending>}
setTimeout(console.log,0,p1===p2)//false
```

##### Promise.prototype.finally()

```js
//给期约方法添加finally处理程序，这个处理程序在期约转为解决或者拒绝状态时都会执行。这个方法可以避免onRejected和onResolved处理程序中出现冗余代码。但onFinally处理程序没有办法知道期约的状态是解决还是拒绝。所以这个方法主要用于清理代码
let p1 = Promise.resolve();
let p2 = Promise.reject();//Uncaught (in promise) undefined
let onFinally = function(){
    setTimeout(console.log,0,'finnally')
}

p1.finally(onFinally)//finnally
p2.finally(onFinally)//finnally

//Promise.prototype.finally()返回一个新的期约实例
let p1 = new Promise(()=>{});
let p2 = p1.finally();

setTimeout(console.log,0,p1)//Promise {<pending>}
setTimeout(console.log,0,p2)//Promise {<pending>}
setTimeout(console.log,0,p1===p2)//false

//这个期约不同于then()或catch()方式返回的实例。因为onFinally是一个与状态无关的方法。无论父期约是解决还是拒绝，都会原样向后传
let p1 = Promise.resolve('foo');
		
//这里都会原样向后传
let p2 = p1.finally();
let p3 = p1.finally(()=>undefined);
let p4 = p1.finally(()=>{});
let p5 = p1.finally(()=>Promise.resolve());
let p6 = p1.finally(()=>'bar');
let p7 = p1.finally(()=>Promise.resolve('bar'));
let p8 = p1.finally(()=>Error('qux'));

setTimeout(console.log,0,p2);//Promise {<resolved>: "foo"}
setTimeout(console.log,0,p3);//Promise {<resolved>: "foo"}
setTimeout(console.log,0,p4);//Promise {<resolved>: "foo"}
setTimeout(console.log,0,p5);//Promise {<resolved>: "foo"}
setTimeout(console.log,0,p6);//Promise {<resolved>: "foo"}
setTimeout(console.log,0,p7);//Promise {<resolved>: "foo"}
setTimeout(console.log,0,p8);//Promise {<resolved>: "foo"}

//如果返回的是一个特定的期约，或者onFinally处理程序抛出了错误，则会返回相应的期约
let p1 = Promise.resolve('foo');
		
//这里都会原样向后传
let p9 = p1.finally(()=>new Promise(()=>{}));
let p10 = p1.finally(()=>Promise.reject());//Uncaught (in promise) undefined

setTimeout(console.log,0,p9);//Promise {<pending>}
setTimeout(console.log,0,p10);//Promise {<rejected>: undefined}
```

##### 非重入期约方法

```js
//当期约进入落定状态时，与该状态相关的处理程序仅会被排期，而非立即执行。跟在处理程序之后的同步代码一定会在处理程序之前先执行。

//在一个解决期约上调用then()会把onResolved处理程序推进消息队列。但这个处理程序在当前线程上的同步代码执行完成前不会执行
let p = Promise.resolve()
p.then(()=>console.log('onresolved'))
console.log('then returns')
//先输出：then returns
//后输出：onresolved

//先添加处理程序后解决期约也是一样的
let asyncResolve;
let p = new Promise((resolve)=>{
    asyncResolve = function(){
        console.log(1)
        resolve();
        console.log(2)
    }
});

p.then(()=>console.log(3))
asyncResolve();
console.log(4)
//1
//2
//4
//3
```

##### 临近处理程序的执行顺序

```js
//如给期约添加了多个处理程序，当期约状态发生改变时，相关处理程序会按照添加的顺序依次执行
//无论是then、catch还是finally都是如此
let p = Promise.resolve();
p.then(()=>console.log(1));
p.then(()=>console.log(2));

//1
//2
```

##### 传递解决值和拒绝理由

```js
//解决的值和拒绝的理由分别作为resolve()和reject()的第一个参数向后传，然后这些值会传给它们各自的处理程序，作为onResolved()和onReject()处理程序的唯一参数。
let p1 = new Promise((resolve,reject)=>resolve('foo'));
//let p1 = Promise.resolve('foo');
p1.then((value)=>console.log(value));//foo

let p2 = new Promise((resolve,reject)=>reject('bar'));
//let p2 = Promise.reject('bar');
p2.catch((value)=>console.log(value));//bar
```

##### 拒绝期约与拒绝错误处理

```js
let p1 = new Promise((resolve,reject)=>reject(Error('foo')))
let p2 = new Promise((resolve,reject)=>{throw Error('foo')})
let p3 = Promise.resolve().then(()=>{throw Error('foo')})
let p4 = Promise.reject(Error('foo'))

setTimeout(console.log,0,p1)//Promise {<rejected>: Error: foo
setTimeout(console.log,0,p2)//Promise {<rejected>: Error: foo
setTimeout(console.log,0,p3)//Promise {<rejected>: Error: foo
setTimeout(console.log,0,p4)//Promise {<rejected>: Error: foo

//也会抛出四个未捕获错误，创建错误对象可以让浏览器捕获错误对象中的栈追踪信息，这些信息对调试非常关键。
//Promise.resolve().then()错误最后才出现，因为它需要在运行时消息队列中添加处理程序
Uncaught (in promise) Error: foo
    at Promise (Untitled2.html:13)
    at new Promise (<anonymous>)
    at Untitled2.html:13
                    
Uncaught (in promise) Error: foo
    at Promise (Untitled2.html:14)
    at new Promise (<anonymous>)
    at Untitled2.html:14
                    
Untitled2.html:16 Uncaught (in promise) Error: foo
	at Untitled2.html:16
        
Uncaught (in promise) Error: foo
    at Promise.resolve.then (Untitled2.html:15)
    at <anonymous>
        
        
//通常在通过throw()关键字抛出错误时，JS的错误处理机制会停止执行抛错后的任何指令
throw Error('foo');
console.log('bar');//不执行
//Uncaught Error:foo

//在期约中抛出错误时，因为错误实际上是从消息队列中异步抛出的，所以并不会阻止运行时继续执行同步指令。
Promise.reject(Error('foo'));
console.log('bar');
//bar
//Uncaught (in promise) Error:foo

//异步错误只能通过异步的onRejected处理程序捕获
//正确
Promise.reject(Error('foo')).catch((e)=>{})

//错误
try{
    Promise.reject(Error('foo'))
}catch(e){}

//在解决或者拒绝期约之前，仍然可以使用try/catch在执行函数中捕获错误
let p = new Promise((resolve,reject)=>{
    try{
        throw Error('foo')
    }catch(e){
        console.log(e)//Error: foo
    }
    resolve('bar')
})

setTimeout(console.log,0,p);//Promise {<resolved>: "bar"}

//onReject处理程序的任务是在捕获异步错误之后返回一个解决的期约
console.log('begin');
try{
    throw Error('foo');
}catch(e){
    console.log('catch error');
}
console.log('continue')
//begin
//catch error
//continue

new Promise((resolve,reject)=>{
    console.log('begin');
    reject(Error('bar'))
}).catch((e)=>{
    console.log('catch error')
}).then(()=>{
    console.log('continue')
})
//begin
//catch error
//continue
```

##### 期约连锁与期约合成

###### 期约连锁

```js
//把期约逐个串联起来
let p = new Promise((resolve,reject)=>{
    console.log('first');
    resolve();
})
p.then(()=>console.log('second'))
.then(()=>console.log('third'))
.then(()=>console.log('fourth'))

//first
//second
//third
//fourth

//上述方法执行了一连串同步任务。这种方式执行的任务没那么有用，因为使用四个同步函数也可以做到
(()=>console.log('first'))();
(()=>console.log('second'))();
(()=>console.log('third'))();
(()=>console.log('fourth'))();

//要真正执行异步任务，让每个执行器都要返回一个期约实例。这样就可以让每个后续期约都等待之前的期约
let p = new Promise((resolve,reject)=>{
    console.log('p1');
    setTimeout(resolve,1000);
})

p.then(()=>new Promise((resolve,reject)=>{
    console.log('p2');
    setTimeout(resolve,1000);
}))
    .then(()=>new Promise((resolve,reject)=>{
    console.log('p3');
    setTimeout(resolve,1000);
}))
    .then(()=>new Promise((resolve,reject)=>{
    console.log('p4');
    setTimeout(resolve,1000);
}))
//1s后 --p1
//2s后 --p2
//3s后 --p3
//4s后 --p4


//生成期约的代码封装到一个工厂函数中
function delayResove(str){
    return new Promise((resolve,reject)=>{
        console.log(str);
        setTimeout(resolve,1000)
    })
}

delayResove('p1')
    .then(()=>delayResove('p2'))
    .then(()=>delayResove('p3'))
    .then(()=>delayResove('p4'))


//如果不使用期约(地狱回调)
function delayExecute(str,callback = null){
    setTimeout(()=>{
        console.log(str);
        callback && callback();
    },1000)
}

delayExecute('p1',()=>{
    delayExecute('p2',()=>{
        delayExecute('p3',()=>{
            delayExecute('p4')
        })
    })
})


//then()/catch()/finally()都返回期约，所以串联这些方法也很直观
let p = new Promise((resolve,reject)=>{
    console.log('init');
    reject();
});

p.catch(()=>console.log('reject'))
    .then(()=>console.log('resolve'))
    .finally(()=>console.log('finally'))
//init
//reject
//resolve
//finally
```

###### 期约图

每个期约可以有任意多个处理程序，所以期约可以构建**有向非循环图**的结构。每一个节点都会等待前一个节点落定。

```js
//注意：期约是按照添加的顺序执行的。由于期约的处理程序是先添加到消息队列，然后才逐个执行。
//     A
//    B  C
//  D E  F G

let A = new Promise((resolve,reject)=>{
    console.log('A');
    resolve();
});
let B = A.then(()=>console.log('B'))
let C = A.then(()=>console.log('C'))

B.then(()=>console.log('D'))
B.then(()=>console.log('E'))
C.then(()=>console.log('F'))
C.then(()=>console.log('G'))
```

###### Promise.all()

```js
//Promise.all()静态方法创建的期约会在一组期约全部解决之后再解决
let p1 = Promise.all([
    Promise.resolve(),
    Promise.resolve()
]);
//可迭代对象中元素会通过Promise.resolve()转换为期约
let p2 = Promise.all([3,4]);
//空的迭代对象等于Promise.resolve()
let p3 = Promise.all([]);
//无效的语法
let p4 = Promise.all();
```

```js
//合成的期约只会在包含的每个期约都解决之后才解决
let p = Promise.all([
    Promise.resolve(),
    new Promise((resolve,reject)=>setTimeout(resolve,1000))
]);

setTimeout(console.log,0,p);//Promise {<pending>}
p.then(()=>setTimeout(console.log,0,'all resolve'));//1s后-all resolve
```

```js
//如果包含至少一个的待定期约，则合成的期约也会待定。如果包含至少一个拒绝的期约，则合成的期约也会拒绝
//永远待定
let p1 = Promise.all([new Promise(()=>{})]);
setTimeout(console.log,0,p1);//Promise {<pending>}

//一次拒绝会导致最终期约拒绝
let p2 = Promise.all([
    Promise.resolve(),
    Promise.reject(),
    Promise.resolve()
])
setTimeout(console.log,0,p2);//Promise {<rejected>: undefined}
//Uncaught (in promise) undefined

//如果所有期约都成功解决，则合成期约的解决值就是包含的所有期约解决值得数组
let p3 = Promise.all([
    Promise.resolve(3),
    Promise.resolve(),
    Promise.resolve(5)
]);
p3.then((values)=>setTimeout(console.log,0,values));//[3, undefined, 5]
```

```js
//如果有期约拒绝，则第一个拒绝的期约会将自己的理由作为合成期约的拒绝理由。之后再拒绝的期约不会影响最终期约的拒绝理由。合成期约会静默处理所有包含期约的拒绝操作
let p = Promise.all([
    Promise.reject(3),
    new Promise((resolve,reject)=>setTimeout(reject,1000))
])
p.catch((reason)=>setTimeout(console.log,0,reason));//3
//没有未处理的错误
```

###### Promise.race()

```js
//Promise.race()静态方法返回一个包装期约，是一组集合找那个最先解决或拒绝的镜像。

let p1 = Promise.race([
    Promise.resolve(),
    Promise.resolve()
]);

//可迭代对象中的元素会通过Promise.resolve()转换为期约
let p2 = Promise.race([3,4]);

//空的可迭代对象等价于new Promise(()=>{})
let p3 = Promise.race([])

//无效
let p4 = Promise.race();//Cannot read property 'Symbol(Symbol.iterator)' of undefined
```

```js
//无论是解决或者拒绝，只要第一个落定的期约，Promise.race()就会包装其值并返回新期约
//解决先发生，后面的拒绝被忽略
let p1 = Promise.race([
    Promise.resolve(3),
    new Promise((resolve,reject)=>setTimeout(reject,1000))
]);
setTimeout(console.log,0,p1);//Promise {<resolved>: 3}

//拒绝先发生，后面的解决被忽略
let p2 = Promise.race([
    Promise.reject(4),
    new Promise((resolve,reject)=>setTimeout(resolve,1000))
]);
setTimeout(console.log,0,p2);//Promise {<rejected>: 4}

//迭代顺序决定了落定顺序
let p3 = Promise.race([
    Promise.resolve(5),
    Promise.resolve(6),
    Promise.resolve(7)
]);
setTimeout(console.log,0,p3);//Promise {<resolved>: 5}
```

```js
//如果有一个期约拒绝，只要它是第一个落定的，就会成为合成期约的拒绝理由。之后再拒绝的期约不会影响最终期约的拒绝理由。合成期约会静默处理所有包含期约的拒绝操作

let p = Promise.race([
    Promise.reject(3),
    new Promise((resolve,reject)=>setTimeout(reject,1000))
])

p.catch((reson)=>setTimeout(console.log,0,reson));//3
//没有未处理的错误
```

###### 串行期约合成

```js
function addTwo(x){return x+2;}
function addThree(x){return x+3;}
function addFive(x){return x+5;}

function addTen(x){
return addFive(addThree(addTwo(x)))
}
console.log(addTen(7));//17

//期约表现形式
function addTen(x){
    return Promise.resolve(x)
        .then(addFive)
        .then(addThree)
        .then(addTwo)
}
addTen(8).then(console.log);//18
```
### 异步函数

也称为"async/await"，让同步写的代码也能异步执行。

#### 异步函数

##### async 

async 关键字用于声明异步函数。这个关键字可以用在函数声明，函数表达式，箭头函数和方法上

```js
async function foo();
let bar = async function(){};
let baz = async ()=>{};
class Qux {
    async qux(){}
}
```

如果异步函数使用return关键字返回了值(没有return则会返回undefined)，这个值会被Promise.resolve()包装成一个期约对象。异步函数始终返回期约对象。

```js
async function foo(){
    console.log(1);
    return 3;//return Promise.resolve(3)
}
foo().then(console.log)
console.log(2);
//1
//2
//3
```

##### await

使用await关键字可以暂停异步函数代码的执行，等待期约解决。

await关键字会暂停执行异步函数后面的代码，让出JS运行时的执行线程。

```js
async function foo(){
    let p = new Promise((resolve,reject)=>setTimeout(resolve,1000,3));
    console.log(await p)
}
foo();
//1s后-3
```

await关键字必须在异步函数中使用，不能在顶级上下文如<script>标签或模块中使用。不过，定义并立即调用异步函数时没问题的。

```js
(async function(){
    console.log(await Promise.resolve(3));
})();
```

异步函数的特质不会扩展到嵌套函数。所以，await关键字也只能直接出现在异步函数的定义中。

#### 停止和恢复执行

```js
async function foo(){
console.log(await Promise.resolve('foo'))
}
async function bar(){
console.log(await 'bar')
}
async function baz(){
console.log('baz')
}

foo();
bar();
baz();
//baz
//bar
//foo
```
真正起作用的是await。async关键字只是一个标识符。异步函数如果不包含await，则跟普通函数一样。



JS运行时会碰到await关键字时，会记录在哪里暂停执行。等到await右边的值可用了，JS运行时会向消息队列中推送一个任务，这个任务会恢复异步函数的执行。

因此，即使await后面跟了一个立即可用的值，函数的其余部分也会被异步求值。

```js

async function foo(){
    console.log(2);
    await null;
    console.log(4);
}
console.log(1);
foo();
console.log(3);

//1
//2
//3
//4

/*
打印1
调用异步函数foo()
打印2
await关键字暂停执行，为立即可用的值，向消息队列添加一个任务
foo()退出
打印3
同步线程执行完毕
JS运行时从消息队列取出任务，恢复异步函数的执行
恢复执行，await取得null值
打印4
foo()返回
*/
```

await后面是一个期约

```js
async function foo(){
    console.log(2);
    console.log(await Promise.resolve(8))
    console.log(9);
}
async function bar(){
    console.log(4);
    console.log(await 6);
    console.log(7);
}

console.log(1);
foo();
console.log(3);
bar();
console.log(5);

//1-2-3-4-5-6-7-8-9
```

#### 异步函数策略

##### 实现sleep()

```js
async function sleep(delay){
    return new Promise((resolve)=>setTimeout(resolve,delay));
}

async function foo(){
    const t0 = Date.now();
    await sleep(1500);
    console.log(Date.now() - t0);
}
foo();
```

##### 串行执行期约

```js
//await直接传递每个函数的返回值，结果通过迭代产生。
function addTwo(x){ return x+2; }
function addThree(x){ return x+3; }
function addFive(x){ return x+5; }

async function addTen(x){
for(const fn of [addTwo,addThree,addFive]){
x = await fn(x);
}
return x;
}

addTen(9).then(console.log);//19
```
```js
//使用期约
async function addTwo(x){ return x+2; }
async function addThree(x){ return x+3; }
async function addFive(x){ return x+5; }

async function addTen(x){
    for(const fn of [addTwo,addThree,addFive]){
        x = await fn(x);
    }
    return x;
}

addTen(9).then(console.log);//19
```

